steps:
  # Step 1: Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/my-app:$COMMIT_SHA",
        ".",
      ]

  # Step 2: Push the Docker image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/my-app:$COMMIT_SHA",
      ]

  # Step 3: Deploy to Cloud Run (without --allow-unauthenticated)
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args: [
        "run",
        "deploy",
        "my-app",
        "--image",
        "us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/my-app:$COMMIT_SHA",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--service-account",
        "ci-service-account@${PROJECT_ID}.iam.gserviceaccount.com", # Specify the service account to use Workload Identity
        "--no-allow-unauthenticated", # Ensures that the service requires authentication
      ]

  # Step 4: Grant the Cloud Run Invoker role to the required service accounts
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args: [
        "run",
        "services",
        "add-iam-policy-binding",
        "my-app",
        "--region",
        "us-central1",
        "--member=serviceAccount:ci-service-account@${PROJECT_ID}.iam.gserviceaccount.com", # Replace with the appropriate service account
        "--role=roles/run.invoker",
      ]

substitutions:
  _SERVICE_NAME: "my-app"
